### ISSUE TITLE
Debian Stretch is not supported

### ISSUE THREAD

**Issue by law** [signalfx/puppet_collectd#56]
Deploying v. 0.1.11 of this module to a freshly-provisioned Debian Stretch host breaks with:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: 
Evaluation Error: Error while evaluating a Function Call, Your Debian OS major release : 9 
is not supported. at 
/etc/puppetlabs/code/environments/production/modules/collectd/manifests/params.pp:82:33 
on node db1-sec.mycorp.com
```

Stretch is the new Stable, does signalfx support that at this time?

**Comment by law** [comment]
Trying to manually add Stretch-type entries to apt results in:
```
Ign:12 https://dl.signalfx.com/debs/collectd/stretch/release  InRelease
Ign:13 https://dl.signalfx.com/debs/signalfx-collectd-plugin/stretch/release  InRelease
Err:14 https://dl.signalfx.com/debs/collectd/stretch/release  Release
  403  Forbidden
Err:15 https://dl.signalfx.com/debs/signalfx-collectd-plugin/stretch/release  Release
  403  Forbidden
Reading package lists... Done 
E: The repository 'https://dl.signalfx.com/debs/collectd/stretch/release  Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://dl.signalfx.com/debs/signalfx-collectd-plugin/stretch/release  Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by molner** [comment]
Hello, @law - thanks for opening an issue. Debian Stretch is not yet supported at this time, only Debian 7 and 8 are currently supported per https://github.com/signalfx/puppet_collectd/blob/master/README.md.

We are hoping to add this support soon. Stay tuned.

**Comment by law** [comment]
thanks.  Is there an ETA available for Stretch support?

**Comment by molner** [comment]
Unfortunately there isn't an ETA available at this time. I will update this issue once one is confirmed.

**Comment by molner** [comment]
@law - I apology for the delay in circling back to this issue, but I wanted to let you know that Debian Stretch support was added a couple weeks back in version 0.1.16 of the SignalFx Puppet Module:
https://forge.puppet.com/signalfx/collectd
