### ISSUE TITLE
Add haproxy support

### ISSUE THREAD

**Issue by mlhess** [signalfx/puppet_collectd#64]
Please add haproxy support.

**Comment by molner** [comment]
Hi @mlhess, thank you for opening an issue for this enhancement. We'll add the request to add haproxy support to our queue, and I'll be sure to notify you here as well via this issue when that has been done.

**Comment by asuresh4** [comment]
Hi @mlhess , we have added HAProxy support with: https://github.com/signalfx/puppet_collectd/pull/65. Please let us know if you have issues using it.
